package constant;

public enum State {
    LOGGED_IN_FILE,
    LOGGED_IN_CONSOLE,
    LOGGED_IN_DATABASE,
    LOGGED_IN_FILE_AND_CONSOLE,
    LOGGED_IN_FILE_AND_DATABASE,
    LOGGED_IN_CONSOLE_AND_DATABASE,
    LOGGED_IN_ALL_LOCATIONS,
    NO_ACTION
}
